name: flutter_apis_pagination
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  kiwi: ^5.0.0
  get_it: ^7.6.7
  shared_preferences: ^2.2.3
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  image_picker: ^1.0.8
  animate_do: ^3.3.4
  flutter_slidable: ^3.1.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  audioplayers: ^5.2.1
  sqflite: ^2.2.6
  path: ^1.8.3
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.1
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_database: ^10.4.9
  firebase_messaging: ^14.7.14
  awesome_notifications: ^0.8.2
  awesome_dialog: ^3.2.1
  curved_navigation_bar: ^1.0.6
  curved_labeled_navigation_bar: ^2.0.2
  device_preview: ^1.1.0
  url_launcher: ^6.3.0
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  flutter_floating_bottom_bar: ^1.2.0
  jwt_decoder: ^2.0.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/translation/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/sounds/
    - assets/videos/
    - assets/lottie/
    - assets/images/category/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: PlayWrite Mexico
      fonts:
        - asset: assets/fonts/playwrite_regular.ttf
    - family: PlayWrite NZ
      fonts:
        - asset: assets/fonts/playwrite_nz_regular.ttf

