import 'package:flutter_apis_pagination/features/advanced_news/bloc.dart';
import 'package:flutter_apis_pagination/features/advanced_news/details/bloc.dart';
import 'package:flutter_apis_pagination/features/g_news/bloc.dart';
import 'package:flutter_apis_pagination/features/login/bloc.dart';
import 'package:flutter_apis_pagination/features/login_regsister/login/bloc.dart';
import 'package:flutter_apis_pagination/features/login_regsister/regsister/bloc.dart';
import 'package:flutter_apis_pagination/features/login_regsister_profile/login/bloc.dart';
import 'package:flutter_apis_pagination/features/login_regsister_profile/profile/bloc.dart';
import 'package:flutter_apis_pagination/features/login_regsister_profile/regsister/bloc.dart';
import 'package:flutter_apis_pagination/features/marvel/bloc.dart';
import 'package:flutter_apis_pagination/features/movie_details/bloc.dart';
import 'package:flutter_apis_pagination/features/movies/bloc.dart';
import 'package:flutter_apis_pagination/features/movies_m/bloc.dart';
import 'package:flutter_apis_pagination/features/movies_m/details/bloc.dart';
import 'package:flutter_apis_pagination/features/movies_pagination/bloc.dart';
import 'package:flutter_apis_pagination/features/new_login/bloc.dart';
import 'package:flutter_apis_pagination/features/new_regsister/bloc.dart';
import 'package:flutter_apis_pagination/features/new_weather/bloc.dart';
import 'package:flutter_apis_pagination/features/news_pagination/bloc.dart';
import 'package:flutter_apis_pagination/features/products/add_product/bloc.dart';
import 'package:flutter_apis_pagination/features/products/all_categories/bloc.dart';
import 'package:flutter_apis_pagination/features/products/all_products/bloc.dart';
import 'package:flutter_apis_pagination/features/products/products_by_category/bloc.dart';
import 'package:flutter_apis_pagination/features/products/update_product/bloc.dart';
import 'package:flutter_apis_pagination/features/signup/bloc.dart';
import 'package:flutter_apis_pagination/features/task_news/bloc.dart';
import 'package:flutter_apis_pagination/features/v_movies/bloc.dart';
import 'package:flutter_apis_pagination/features/v_movies/details/bloc.dart';
import 'package:flutter_apis_pagination/features/v_weather/bloc.dart';
import 'package:flutter_apis_pagination/features/w_weather/bloc.dart';
import 'package:flutter_apis_pagination/features/weather/bloc.dart';
import 'package:flutter_apis_pagination/features/weather_task/bloc.dart';
import 'package:flutter_apis_pagination/features/y_movies/movies/bloc.dart';
import 'package:flutter_apis_pagination/features/y_weather/bloc.dart';
import 'package:flutter_apis_pagination/features/z_movies/bloc.dart';
import 'package:flutter_apis_pagination/features/z_movies/details/bloc.dart';
import 'package:get_it/get_it.dart';

void initGetIt(){
  final getit=GetIt.instance;

  getit.registerFactory(() => LoginBloc());
  getit.registerFactory(() => RegsisterBloc());
  getit.registerFactory(() => MoviesBloc());
  getit.registerFactory(() => MovieDetailsBloc());
  getit.registerFactory(() => PMoviesBloc());
  getit.registerFactory(() => NewsBloc());
  getit.registerFactory(() => WeatherBloc());
  getit.registerFactory(() => ANewsBloc());
  getit.registerFactory(() => AdMoviesBloc());
  getit.registerFactory(() => AdMovieDetailsBloc());
  getit.registerFactory(() => MWeatherBloc());
  getit.registerFactory(() => GNewsBloc());
  getit.registerFactory(() => NLoginBloc());
  getit.registerFactory(() => NRegsisterBloc());
  getit.registerFactory(() => TWeatherBloc());
  getit.registerFactory(() => MoviesMBloc());
  getit.registerFactory(() => MovieMDetailsBloc());
  getit.registerFactory(() => VLoginBloc());
  getit.registerFactory(() => VRegsisterBloc());
  getit.registerFactory(() => VProfileBloc());
  getit.registerFactory(() => VMoviesBloc());
  getit.registerFactory(() => VMovieDetailsBloc());
  getit.registerFactory(() => AllProductsBloc());
  getit.registerFactory(() => VWeatherBloc());
  getit.registerFactory(() => AllCategoriesBloc());
  getit.registerFactory(() => ProductsByCategoryBloc());
  getit.registerFactory(() => AddProductBloc());
  getit.registerFactory(() => UpdateProductBloc());
  getit.registerFactory(() => WWeatherBloc());
  getit.registerFactory(() => ZMoviesBloc());
  getit.registerFactory(() => ZMovieDetailsBloc());
  getit.registerFactory(() => ALoginBloc());
  getit.registerFactory(() => ASignupBloc());
  getit.registerFactory(() => YMoviesBloc());
  getit.registerFactory(() => YWeatherBloc());
  getit.registerFactory(() => MarvelBloc());
}