import 'package:flutter_apis_pagination/features/advanced_news/bloc.dart';
import 'package:flutter_apis_pagination/features/advanced_news/details/bloc.dart';
import 'package:flutter_apis_pagination/features/g_news/bloc.dart';
import 'package:flutter_apis_pagination/features/login/bloc.dart';
import 'package:flutter_apis_pagination/features/login_regsister/login/bloc.dart';
import 'package:flutter_apis_pagination/features/login_regsister/regsister/bloc.dart';
import 'package:flutter_apis_pagination/features/login_regsister_profile/login/bloc.dart';
import 'package:flutter_apis_pagination/features/login_regsister_profile/profile/bloc.dart';
import 'package:flutter_apis_pagination/features/login_regsister_profile/regsister/bloc.dart';
import 'package:flutter_apis_pagination/features/marvel/bloc.dart';
import 'package:flutter_apis_pagination/features/movie_details/bloc.dart';
import 'package:flutter_apis_pagination/features/movies/bloc.dart';
import 'package:flutter_apis_pagination/features/movies_m/bloc.dart';
import 'package:flutter_apis_pagination/features/movies_m/details/bloc.dart';
import 'package:flutter_apis_pagination/features/movies_pagination/bloc.dart';
import 'package:flutter_apis_pagination/features/new_login/bloc.dart';
import 'package:flutter_apis_pagination/features/new_regsister/bloc.dart';
import 'package:flutter_apis_pagination/features/new_weather/bloc.dart';
import 'package:flutter_apis_pagination/features/news_pagination/bloc.dart';
import 'package:flutter_apis_pagination/features/products/add_product/bloc.dart';
import 'package:flutter_apis_pagination/features/products/all_categories/bloc.dart';
import 'package:flutter_apis_pagination/features/products/all_products/bloc.dart';
import 'package:flutter_apis_pagination/features/products/products_by_category/bloc.dart';
import 'package:flutter_apis_pagination/features/products/update_product/bloc.dart';
import 'package:flutter_apis_pagination/features/signup/bloc.dart';
import 'package:flutter_apis_pagination/features/task_news/bloc.dart';
import 'package:flutter_apis_pagination/features/v_movies/bloc.dart';
import 'package:flutter_apis_pagination/features/v_movies/details/bloc.dart';
import 'package:flutter_apis_pagination/features/v_weather/bloc.dart';
import 'package:flutter_apis_pagination/features/w_weather/bloc.dart';
import 'package:flutter_apis_pagination/features/weather/bloc.dart';
import 'package:flutter_apis_pagination/features/weather_task/bloc.dart';
import 'package:flutter_apis_pagination/features/y_movies/movies/bloc.dart';
import 'package:flutter_apis_pagination/features/y_weather/bloc.dart';
import 'package:flutter_apis_pagination/features/z_movies/bloc.dart';
import 'package:flutter_apis_pagination/features/z_movies/details/bloc.dart';
import 'package:kiwi/kiwi.dart';

void initKiwi(){
  final kiwi=KiwiContainer();

  kiwi.registerFactory((container) => LoginBloc());
  kiwi.registerFactory((container) => RegsisterBloc());
  kiwi.registerFactory((container) => MoviesBloc());
  kiwi.registerFactory((container) => MovieDetailsBloc());
  kiwi.registerFactory((container) => PMoviesBloc());
  kiwi.registerFactory((container) => NewsBloc());
  kiwi.registerFactory((container) => WeatherBloc());
  kiwi.registerFactory((container) => ANewsBloc());
  kiwi.registerFactory((container) => AdMoviesBloc());
  kiwi.registerFactory((container) => AdMovieDetailsBloc());
  kiwi.registerFactory((container) => MWeatherBloc());
  kiwi.registerFactory((container) => GNewsBloc());
  kiwi.registerFactory((container) => NLoginBloc());
  kiwi.registerFactory((container) => NRegsisterBloc());
  kiwi.registerFactory((container) => TWeatherBloc());
  kiwi.registerFactory((container) => MoviesMBloc());
  kiwi.registerFactory((container) => MovieMDetailsBloc());
  kiwi.registerFactory((container) => VLoginBloc());
  kiwi.registerFactory((container) => VRegsisterBloc());
  kiwi.registerFactory((container) => VProfileBloc());
  kiwi.registerFactory((container) => VMoviesBloc());
  kiwi.registerFactory((container) => VMovieDetailsBloc());
  kiwi.registerFactory((container) => AllProductsBloc());
  kiwi.registerFactory((container) => VWeatherBloc());
  kiwi.registerFactory((container) => AllCategoriesBloc());
  kiwi.registerFactory((container) => ProductsByCategoryBloc());
  kiwi.registerFactory((container) => AddProductBloc());
  kiwi.registerFactory((container) => UpdateProductBloc());
  kiwi.registerFactory((container) => WWeatherBloc());
  kiwi.registerFactory((container) => ZMoviesBloc());
  kiwi.registerFactory((container) => ZMovieDetailsBloc());
  kiwi.registerFactory((container) => ALoginBloc());
  kiwi.registerFactory((container) => ASignupBloc());
  kiwi.registerFactory((container) => YMoviesBloc());
  kiwi.registerFactory((container) => YWeatherBloc());
  kiwi.registerFactory((container) => MarvelBloc());
}